Added improvements to boolean dropdowns
uclaacm/boolbots pull request #40
Opened 2021-07-13 21:44 UTC by connord28

2021-07-14 05:22 UTC, reginawang99 reviewed
descriptive names for PRs are good (not only for reviewer, but also since it transfers to commit name in the repo).

Could you change the name of the PR to something like `add visual improvements to boolean dropdowns` or `add visual improvements to boolean dropdowns such as highlighting hover`?

2021-07-14 05:22 UTC, reginawang99 commented on src/styles/booleanDropdown.scss
> +
```suggestion
```

2021-07-14 05:22 UTC, reginawang99 commented on src/styles/booleanDropdown.scss
> +
```suggestion
```

2021-07-14 05:22 UTC, reginawang99 commented on src/styles/booleanDropdown.scss
> +  background-color: #adadad;
this seems to be the general hover color (even in `levelSelect.scss`), can we pull it out and put it in `global.scss`?

2021-07-14 17:26 UTC, nendow02 requested changes

2021-07-14 17:26 UTC, nendow02 commented on src/styles/booleanDropdown.scss
>    background-color: lightgray;
Can we also put this in `global.scss`, since the dropdowns in the "experiment" page will use the same colors.

2021-07-14 17:26 UTC, nendow02 commented on src/styles/booleanDropdown.scss
> +  background-color: #adadad;
Same thing that Regina mentioned

2021-07-14 22:48 UTC, nendow02 approved these changes
Looks good to me, thanks for making the changes!

2021-07-15 08:18 UTC, reginawang99 commented
Can you rename the PR as per above comment?

2021-07-15 20:24 UTC, reginawang99 requested changes
just a small idea for reusing code more

2021-07-16 05:07 UTC, reginawang99 commented on src/styles/booleanDropdown.scss
> +
you can have a `.arrow` class <for all overlapping> and a `flipped` class for just the `transform` part

2021-07-16 13:43 UTC, reginawang99 approved these changes
LGTM! Congrats on first PR to boolbots 🥳🎉

2021-07-16 20:24 UTC, merged